"""init migration

Revision ID: 6ff06b808b53
Revises: 
Create Date: 2025-03-29 00:55:06.686431

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6ff06b808b53'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cars',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('driven', sa.Integer(), nullable=False),
    sa.Column('mileage', sa.Float(), nullable=False),
    sa.Column('engine', sa.Integer(), nullable=False),
    sa.Column('hp', sa.Float(), nullable=False),
    sa.Column('seats', sa.Integer(), nullable=False),
    sa.Column('price', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_cars_id'), 'cars', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_cars_id'), table_name='cars')
    op.drop_table('cars')
    # ### end Alembic commands ###
